//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public collection()
        {
            this.stories = new HashSet<story>();
            this.sets = new HashSet<set>();
            this.groups = new HashSet<group>();
            this.collection_photos = new HashSet<collection_photos>();
        }
    
        public int collection_id { get; set; }
        public string collection_name { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
    
        public virtual ICollection<story> stories { get; set; }
        public virtual ICollection<set> sets { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<collection_photos> collection_photos { get; set; }
    }
}
