//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_photos
    {
        public int id { get; set; }
        public int photo_id { get; set; }
        public int collection_id { get; set; }
        public System.DateTime added_on { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual photo photo { get; set; }
    }
}
