//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.story_comments = new HashSet<story_comments>();
            this.photo_comments = new HashSet<photo_comments>();
        }
    
        public int comment_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime comment_datetime { get; set; }
        public string comment_text { get; set; }
    
        public virtual ICollection<story_comments> story_comments { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<photo_comments> photo_comments { get; set; }
    }
}
