//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int id { get; set; }
        public int photo_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> fav_datetime { get; set; }
    
        public virtual photo photo { get; set; }
        public virtual user user { get; set; }
    }
}
