//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.group_members = new HashSet<group_members>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> collection_id { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual ICollection<group_members> group_members { get; set; }
    }
}
