//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        public membership()
        {
            this.users = new HashSet<user>();
        }
    
        public int membership_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string is_approved { get; set; }
        public Nullable<System.DateTime> joined_date { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
