//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class photoshareEntities : DbContext
    {
        public photoshareEntities()
            : base("name=photoshareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<collection> collections { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<exif_data> exif_data { get; set; }
        public DbSet<follower> followers { get; set; }
        public DbSet<group_members> group_members { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<membership> memberships { get; set; }
        public DbSet<photo_comments> photo_comments { get; set; }
        public DbSet<photo> photos { get; set; }
        public DbSet<set> sets { get; set; }
        public DbSet<story> stories { get; set; }
        public DbSet<story_comments> story_comments { get; set; }
        public DbSet<user_activity> user_activity { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<favorite> favorites { get; set; }
        public DbSet<collection_photos> collection_photos { get; set; }
        public DbSet<like> likes { get; set; }
    
        public virtual int spPhotoDelete(Nullable<int> photoId)
        {
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("photoId", photoId) :
                new ObjectParameter("photoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPhotoDelete", photoIdParameter);
        }
    }
}
