//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class story
    {
        public story()
        {
            this.story_comments = new HashSet<story_comments>();
        }
    
        public int story_id { get; set; }
        public int collection_id { get; set; }
        public string description { get; set; }
        public string tags { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual ICollection<story_comments> story_comments { get; set; }
    }
}
